# Sources
---
-
  name: craigslist
  url:  "http://boston.craigslist.org/jsonsearch/aap/"
  geographic_fields:
    - 
      name: 'r["Longitude"], r["Latitude"]'
      type: Point
  map_fields:
    bedrooms: "Bedrooms"
    date: 'DateTime.strptime r["PostedDate"], "%s"'
